### PR TITLE
Readme: Minor fixes

### PR DESCRIPTION
**Pull request by GaryJones**

### CODE REVIEW

**Comment by GaryJones** [comment]
Bump.

**Comment by GaryJones** [comment]
Bump.

**Comment by GaryJones** [comment]
Bump.

**Comment by GaryJones** [comment]
Bump.

**Comment by Misplon** [comment]
Thanks Gary. I still love using this library so it would be awesome if PR's were checked and merged. Just to keep things moving forward a bit. Hopefully Devin will be able to take a look soon.

**Comment by GaryJones** [comment]
Closing for lack of interest.

**Pull request closed without merging**
